### ISSUE TITLE
Ability to create new menus from admin interface

### ISSUE THREAD

**Issue by jokklan** [pylonweb/refinerycms-menus#2]
For helping developing. Should not be used in production, as there is no way to show the newly created menus on site.

**Comment by bricesanchez** [comment]
I would like to say that this gem forked by @matfiz works well with refinerycms 2.0.5. (There is a bug when we edit a custom menu, we always see the data of the main menu when we "Edit this menu")

I added manually new menus in the DB in the "refinery_page_menus" table because there is no admin interface.

How is your work in order to create new menus with the admin interface ? 
Could you update your code soon ? 
Or do you need some help ?

**Comment by agentGreg** [comment]
Hi @bricesanchez,

So far I am adding this through rails console... I am on holidays now, so if you have some time to contribute with this functionality, I will be really glad!

**Comment by jokklan** [comment]
Sorry i haven't answered in some time... i have leaved this project (at least for now), in favor of the solution discussed here: https://github.com/resolve/refinerycms/issues/1341, that hopefully will come in a near future version of refinerycms

**Comment by agentGreg** [comment]
Cool, thanks for the news!

**Comment by bricesanchez** [comment]
Thanks too for the news.

**Comment by jokklan** [comment]
The project have started up again :p
However, I don't think it would ever be appropriate to create new menus in the interface, as there is no way to implement them in them on the frontend without changing the code. Maybe a rake task instead to help developers.

**Comment by jokklan** [comment]
Fixed with 4343b2134a21e5023bfe9817a19e38432001f97b
