### ISSUE TITLE
2.1.0.dev support

### ISSUE THREAD

**Issue by mattolson** [pylonweb/refinerycms-menus#31]
I'm working on this now

**Comment by jokklan** [comment]
Sounds good. Im releasing 2.0.7 in a few minutes, when my tests is passing, which should fix #32, so use that as reference point.

**Comment by mattolson** [comment]
OK, I grabbed 2.0.7 and started messing with it. The first thing I ran into is "superclass mismatch for class MenuItem", which appears to be due to this change: refinery/refinerycms@b507ee5a16d46bbc57400b388e204c7f20101231

I think supporting 2.1.0.dev will require quite a few changes to make it play well with the new MenuPresenter code. See #15. 

I'll dig a little deeper, but any thoughts?

**Comment by jokklan** [comment]
The "superclass mismatch" is because MenuItem doesn't extends `HashWithIndifferentAccess` anymore and we decorate it, see [menu_item_decorator.rb](https://github.com/pylonweb/refinerycms-menus/blob/master/lib/refinery/menu_item_decorator.rb).

I think most of the changes will be to the [menu_item_decorator.rb](https://github.com/pylonweb/refinerycms-menus/blob/master/lib/refinery/menu_item_decorator.rb), [menus.rb](https://github.com/pylonweb/refinerycms-menus/blob/master/lib/refinery/menus.rb) and [instance_methods.rb](https://github.com/pylonweb/refinerycms-menus/blob/master/lib/refinery/menus/instance_methods.rb) files, in the lib directory.

**Comment by jokklan** [comment]
Closing this now. See #33
